// Generated by using rustinr::rustrize() -> do not edit by hand

use super::*;

#[no_mangle]
pub extern "C" fn rustr_vec_check(a : SEXP, b : SEXP)->SEXP{

 let a_ : Vec<u64> = unwrapr!( Vec::rnew(a) );

let b_ : Vec<u64> = unwrapr!( Vec::rnew(b) );
 let res  = vec_check(& a_,& b_);

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}

