// Generated by using rustinr::rustrize() -> do not edit by hand

use super::*;

#[no_mangle]
pub extern "C" fn rustr_check_covering(r : SEXP, m : SEXP)->SEXP{

 let r_ : Vec<u64> = unwrapr!( Vec::rnew(r) );

let m_ : Vec<u64> = unwrapr!( Vec::rnew(m) );
 let res  = check_covering(& r_,& m_);

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}

