// Generated by using rustinr::rustrize() -> do not edit by hand

#include <Rinternals.h>
#include <R.h>

extern SEXP rustr_check_covering(SEXP a, SEXP b);
SEXP coveR_check_covering(SEXP a, SEXP b){ return(rustr_check_covering(a,b));}
