// Generated by using rustinr::rustrize() -> do not edit by hand

#include <Rinternals.h>
#include <R.h>

extern SEXP rustr_vec_check(SEXP a, SEXP b);
SEXP coveR_vec_check(SEXP a, SEXP b){ return(rustr_vec_check(a,b));}
