// Generated by using rustinr::rustrize() -> do not edit by hand

#include <Rinternals.h>
#include <R.h>

extern SEXP rustr_check_covering(SEXP r, SEXP m);
SEXP coveR_check_covering(SEXP r, SEXP m){ return(rustr_check_covering(r,m));}
