# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title session_count
#' @description Session counting function
#' 
#' @details Blarg
#' @export
rcpp_hello_world <- function() {
    .Call('coveR_rcpp_hello_world', PACKAGE = 'coveR')
}

