# Generated by using rustinr::rustrize() -> do not edit by hand

#' Check a covering for a set of moduli and residuals
#' 
#' Checks whether or not a set of residuals and moduli.  Both parameters 
#' (r and m) must be integer vectors; use \code{\link{as.integer}} to convert 
#' generic numeric vectors to integer vectors.
#'
#' @param r an integer vector containing residuals
#' @param m an integer vector containing the moduli
#' @return a single boolean value
#'
#' @export
check_covering = function(r,m){ .Call('coveR_check_covering',PACKAGE = 'coveR', r,m)}
